spring:
  application:
    name=jwt-authentication-model


  flyway:
    baseline-on-migrate: true
    baseline-version: 1


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt-authentication?useTimezone=true&serverTimezone=UTC
    username: root
    password: 91446432

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true

api:
  security:
    jwt:
      secret: mySecretKey

logging:
  level:
    org.springframework.security: DEBUG
